/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markorganizer;

/**
 *
 * @author Zohra
 */

import java.text.DecimalFormat;
import java.util.ArrayList; 
import java.util.Collections;
public class Calculator extends javax.swing.JFrame {
ArrayList<Double> testmarks = new ArrayList<Double>();
ArrayList<Double> quizmarks = new ArrayList<Double>();
ArrayList<String> testmarksstring = new ArrayList<String>();
ArrayList<String> quizmarksstring = new ArrayList<String>();
ArrayList<Double> testmarkssorted = new ArrayList<Double>();
double testaverage;
double quizaverage;
String testaverageString;
String quizaverageString;
double testTotal = 0;
double quizTotal = 0;
String testworth;
double median;
FileSetup no = new FileSetup();
/**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        Error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Testmark = new javax.swing.JLabel();
        Quizmark1 = new javax.swing.JLabel();
        Quizmark2 = new javax.swing.JLabel();
        Testmarkinput = new javax.swing.JTextField();
        Quizmark1input = new javax.swing.JTextField();
        Quizmark2input = new javax.swing.JTextField();
        Testaverage = new javax.swing.JLabel();
        Quizaverage = new javax.swing.JLabel();
        Testaveragedisplay = new javax.swing.JTextField();
        Quizaveragedisplay = new javax.swing.JTextField();
        thantestaverage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Testmedian = new javax.swing.JLabel();
        Mediandisplay = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Restart = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        Finish = new javax.swing.JButton();
        Continue = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Enter marks here", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        Testmark.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Testmark.setText("Test mark:");

        Quizmark1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quizmark1.setText("Quiz mark:");

        Quizmark2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quizmark2.setText("Quiz mark:");

        Testmarkinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestmarkinputActionPerformed(evt);
            }
        });

        Quizmark1input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quizmark1inputActionPerformed(evt);
            }
        });

        Quizmark2input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quizmark2inputActionPerformed(evt);
            }
        });

        Testaverage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Testaverage.setText("Test average is: ");

        Quizaverage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quizaverage.setText("Quiz average is: ");

        Quizaveragedisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizaveragedisplayActionPerformed(evt);
            }
        });

        thantestaverage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thantestaverage.setText("than test average");

        jLabel7.setText("/100");

        jLabel8.setText("/100");

        jLabel9.setText("/100");

        jLabel10.setText("/100");

        Testmedian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Testmedian.setText("Test median is:");

        Mediandisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediandisplayActionPerformed(evt);
            }
        });

        jLabel12.setText("/100");

        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        Error.setText("Invalid input");

        Finish.setText("Finish and display average");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        Continue.setText("Continue?");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });

        jLabel1.setText("unit tests entered");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Testmark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Testmarkinput, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(Error))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Testmedian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mediandisplay))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Testaverage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Testaveragedisplay))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Quizaverage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quizaveragedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thantestaverage)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Quizmark1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Quizmark1input, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Quizmark2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Quizmark2input, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Continue)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Finish))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Restart)
                            .addComponent(jLabel1))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Testmark)
                    .addComponent(Testmarkinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Quizmark1)
                        .addComponent(Quizmark1input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Quizmark2)
                        .addComponent(Quizmark2input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Restart)
                    .addComponent(Finish)
                    .addComponent(Continue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Testaverage)
                    .addComponent(Testaveragedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quizaverage)
                    .addComponent(Quizaveragedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thantestaverage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Testmedian)
                    .addComponent(Mediandisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TestmarkinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestmarkinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestmarkinputActionPerformed

    private void Quizmark1inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quizmark1inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quizmark1inputActionPerformed

    private void Quizmark2inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quizmark2inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quizmark2inputActionPerformed

    private void QuizaveragedisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizaveragedisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuizaveragedisplayActionPerformed

    private void MediandisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediandisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MediandisplayActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        // TODO add your handling code here:
        testmarks.clear();
        quizmarks.clear();
        Testmarkinput.setText("");
        Quizmark1input.setText("");
        Quizmark2input.setText("");
    }//GEN-LAST:event_RestartActionPerformed

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        // TODO add your handling code here:
        for(double c: testmarks){
            testTotal += c;
        }
        for(double d: quizmarks){
            quizTotal += d;
        }
        if(quizaverage>testaverage){
            Quizaveragedisplay.setText("higher");
        }else{
            Quizaveragedisplay.setText("lower");
        }
        Testaveragedisplay.setText(String.valueOf(testaverage));
        testmarkssorted = testmarks;
        Collections.sort(testmarkssorted);
        double sortlen = testmarks.size();
        if(sortlen % 2 == 0){
            median = (testmarkssorted.get(testmarks.size()/2) + testmarkssorted.get(testmarks.size()/2 + 1))/2;
            Mediandisplay.setText(String.valueOf(median));
        }else{
            int middle = Integer.parseInt(String.valueOf(sortlen/2 + 0.5));
            median = testmarkssorted.get(middle);
        }
    }//GEN-LAST:event_FinishActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
        if(Testmarkinput.getText().isEmpty()){
            Error.setVisible(true);
            Testmarkinput.setText("");
            Quizmark1input.setText("");
            Quizmark2input.setText("");
        }else if(Quizmark1input.getText().isEmpty()){
            Error.setVisible(false);
            try{
                testmarks.add(Double.parseDouble(Testmarkinput.getText()));
                quizmarks.add(Double.parseDouble(Quizmark2input.getText()));
                
            }catch(NumberFormatException e){
                Error.setVisible(true);
                Testmarkinput.setText("");
                Quizmark1input.setText("");
                Quizmark2input.setText("");
            }
            Testmarkinput.setText("");
            Quizmark1input.setText("");
            Quizmark2input.setText("");
        }else if(Quizmark2input.getText().isEmpty()){
            Error.setVisible(false);
            try{
                testmarks.add(Double.parseDouble(Testmarkinput.getText()));
                quizmarks.add(Double.parseDouble(Quizmark1input.getText()));
            }catch(NumberFormatException e){
                Error.setVisible(true);
                Testmarkinput.setText("");
                Quizmark1input.setText("");
                Quizmark2input.setText("");
            }
            Testmarkinput.setText("");
            Quizmark1input.setText("");
            Quizmark2input.setText("");
        }else if(Quizmark1input.getText().isEmpty() && Quizmark2input.getText().isEmpty()){
            Error.setVisible(false);
            try{
                testmarks.add(Double.parseDouble(Testmarkinput.getText()));
            }catch(NumberFormatException e){
                Error.setVisible(true);
                Testmarkinput.setText("");
                Quizmark1input.setText("");
                Quizmark2input.setText("");
            }
            Testmarkinput.setText("");
            Quizmark1input.setText("");
            Quizmark2input.setText("");
        }
    }//GEN-LAST:event_ContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Calculator ec = new Calculator();
        DecimalFormat mark = new DecimalFormat("##.##");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
        ec.testaverage = ec.testTotal/ec.testmarks.size();
        ec.quizaverage = ec.quizTotal/ec.quizmarks.size();
        ec.quizaverageString = String.valueOf(ec.quizaverage);
        ec.testaverageString = String.valueOf(ec.testaverage);
        ec.testworth = mark.format((ec.testaverage/100) * 70);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JLabel Error;
    private javax.swing.JButton Finish;
    private javax.swing.JTextField Mediandisplay;
    private javax.swing.JLabel Quizaverage;
    private javax.swing.JTextField Quizaveragedisplay;
    private javax.swing.JLabel Quizmark1;
    private javax.swing.JTextField Quizmark1input;
    private javax.swing.JLabel Quizmark2;
    private javax.swing.JTextField Quizmark2input;
    private javax.swing.JButton Restart;
    private javax.swing.JLabel Testaverage;
    private javax.swing.JTextField Testaveragedisplay;
    private javax.swing.JLabel Testmark;
    private javax.swing.JTextField Testmarkinput;
    private javax.swing.JLabel Testmedian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel thantestaverage;
    // End of variables declaration//GEN-END:variables
}
